# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ci-cd-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://containersimpleapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_694058c3326746b1997f36c2b343f83e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_315b133104fc434895e4b68ddcb04e12 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: containersimpleapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_694058c3326746b1997f36c2b343f83e }}/deployazurecicddocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ci-cd-azure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_83af63153f9a488eb4b839e42784318c }}
        images: 'containersimpleapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_694058c3326746b1997f36c2b343f83e }}/deployazurecicddocker:${{ github.sha }}'